# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba56f308e91244137c8ea900fe391ecfbdb2919a53c4c8c112b2a4d283118ea3d5cf3d2b793a0bdf596debe2fc3d214cfdcde61622f75a5344ad86e6e4a1c6c4

test:
  secret_key_base: 662fec0c967f6d79837790ea45dee29f32bee4827e11552d066edba8c11dd8e0360c285eb1a007bc7d753902f93ffc0a9f894c1fd823b59d34c2100e2c2515b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
